// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YWJ3fpOyfP3NFh5fUHzZuWkXY-HenTo',
    appId: '1:386439708122:web:0daee2907ffd80db5254e3',
    messagingSenderId: '386439708122',
    projectId: 'laundrymobile-9335f',
    authDomain: 'laundrymobile-9335f.firebaseapp.com',
    storageBucket: 'laundrymobile-9335f.appspot.com',
    measurementId: 'G-DC7LSF0HL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLdfwb2xttHRc_lwIBCjYJHvKJwmlhrw',
    appId: '1:386439708122:android:11bce399ce19ff925254e3',
    messagingSenderId: '386439708122',
    projectId: 'laundrymobile-9335f',
    storageBucket: 'laundrymobile-9335f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYuvsimXULyofkQZ45LhKrq-AU2suTSmw',
    appId: '1:386439708122:ios:ec8a0f4d2f540d4c5254e3',
    messagingSenderId: '386439708122',
    projectId: 'laundrymobile-9335f',
    storageBucket: 'laundrymobile-9335f.appspot.com',
    androidClientId: '386439708122-117ra1t7m1hcs4aglsf9sr3oq8dqcl6g.apps.googleusercontent.com',
    iosClientId: '386439708122-dom8nktlusidd6d4d08irsfnlfia1j2t.apps.googleusercontent.com',
    iosBundleId: 'com.adisorndev.laundryMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYuvsimXULyofkQZ45LhKrq-AU2suTSmw',
    appId: '1:386439708122:ios:db8413852937935a5254e3',
    messagingSenderId: '386439708122',
    projectId: 'laundrymobile-9335f',
    storageBucket: 'laundrymobile-9335f.appspot.com',
    androidClientId: '386439708122-117ra1t7m1hcs4aglsf9sr3oq8dqcl6g.apps.googleusercontent.com',
    iosClientId: '386439708122-flvs7omdb2nqv27nmbf8hrkkfr82ampm.apps.googleusercontent.com',
    iosBundleId: 'com.adisorndev.laundryMobile.RunnerTests',
  );
}
