const List<String> thaiProvinces = [
  'Bangkok',
  'Krabi',
  'Kanchanaburi',
  'Kalasin',
  'Kamphaeng Phet',
  'Khon Kaen',
  'Chanthaburi',
  'Chachoengsao',
  'Chonburi',
  'Chainat',
  'Chaiyaphum',
  'Chumphon',
  'Chiang Rai',
  'Chiang Mai',
  'Trang',
  'Trat',
  'Tak',
  'Nakhon Nayok',
  'Nakhon Pathom',
  'Nakhon Phanom',
  'Nakhon Ratchasima',
  'Nakhon Si Thammarat',
  'Nakhon Sawan',
  'Nonthaburi',
  'Narathiwat',
  'Nan',
  'Bueng Kan',
  'Buri Ram',
  'Pathum Thani',
  'Prachuap Khiri Khan',
  'Prachin Buri',
  'Pattani',
  'Phra Nakhon Si Ayutthaya',
  'Phang Nga',
  'Phatthalung',
  'Phichit',
  'Phitsanulok',
  'Phetchaburi',
  'Phetchabun',
  'Phrae',
  'Phayao',
  'Phuket',
  'Maha Sarakham',
  'Mukdahan',
  'Mae Hong Son',
  'Yasothon',
  'Yala',
  'Roi Et',
  'Ranong',
  'Rayong',
  'Ratchaburi',
  'Lopburi',
  'Lampang',
  'Lamphun',
  'Loei',
  'Si Sa Ket',
  'Sakon Nakhon',
  'Songkhla',
  'Satun',
  'Samut Prakan',
  'Samut Songkhram',
  'Samut Sakhon',
  'Sa Kaeo',
  'Saraburi',
  'Sing Buri',
  'Sukhothai',
  'Suphan Buri',
  'Surat Thani',
  'Surin',
  'Nong Khai',
  'Nong Bua Lamphu',
  'Ang Thong',
  'Amnat Charoen',
  'Udon Thani',
  'Uttaradit',
  'Uthai Thani',
  'Ubon Ratchathani'
];
